Diplomka/Pages/AboutUs.cshtml.cs
using Diplomka.Models;
using Microsoft.AspNetCore.Cors;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;

namespace Diplomka.Pages
{
    public class AboutUsModel : PageModel
    {
        private readonly DiplomDBContext _context;
        [BindProperty]
        public string Name { get; set; }

        [BindProperty]
        public string Email { get; set; }

        [BindProperty]
        public string Message { get; set; }

        [BindProperty]
        public DateTime Date { get; set; }

        public AboutUsModel(DiplomDBContext context)
        {
            this._context = context;
        }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostSendForm()
        {
            if (!string.IsNullOrEmpty(Name) && !string.IsNullOrEmpty(Email) && !string.IsNullOrEmpty(Message))
            {
                Resume resume = new Resume();

                resume.Id = Guid.NewGuid().ToString().ToUpper();
                resume.AuthorName = Name;
                resume.Email = Email;
                resume.About = Message;
                resume.Birthday = Date;

                _context.Resumes.Add(resume);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("Index");
        }
    }
}

Diplomka/Pages/AnalyzePage.cshtml.cs
using Diplomka.Models; 
using Microsoft.AspNetCore.Mvc; 
using Microsoft.AspNetCore.Mvc.RazorPages; 
using Microsoft.Data.SqlClient; 
using Newtonsoft.Json.Linq; 
using System.Text; 
 
namespace Diplomka.Pages
{
    public class AnalyzePageModel : PageModel
    {
        private readonly string _dbConnection;

        private readonly DiplomDBContext _context;

        [BindProperty(SupportsGet = true)]
        public string Number { get; set; }

        [BindProperty(SupportsGet = true)]
        public string Points { get; set; }

        public List<ENTPrediction> entPredictions = new List<ENTPrediction>();

        public List<string> UniversitiesNames = new List<string>();

        public string SubjectName { get; set; }

        public AnalyzePageModel(DiplomDBContext context)
        {
            this._dbConnection = "Server=(localdb)\\MSSQLLocalDB; Database=DBDiplom; Trusted_Connection=True;";
            this._context = context;
        }
        public void OnGet()
        {
            StringBuilder sbResult = new StringBuilder();
            StringBuilder sbQuery = new StringBuilder();

            sbQuery.Append("SELECT CodeName, Description " +
                           "FROM EducationPrCode " +
                           "WHERE Id IN (SELECT EducationCodeId " +
                           "             FROM EducationProgram " +
                           "             WHERE SubjId = (SELECT Id" +
            "                             FROM Subjects" +
                           "                             WHERE Number = '" + Number + "'));");

            using (SqlConnection sqlConnection = new SqlConnection(this._dbConnection))
            {
                sqlConnection.Open();

                SqlCommand command = new SqlCommand(sbQuery.ToString(), sqlConnection);
                SqlDataReader reader = command.ExecuteReader();

                if (reader.HasRows)
                {
                    while (reader.Read())
                    {
                        string codeName = reader.GetValue(0).ToString();
                        string description = reader.GetValue(1).ToString();
                        int prediction = 0;
                        int point = Convert.ToInt32(Points);

                        StringBuilder sbQueryAVG = new StringBuilder();
                        sbQueryAVG.Append($"SELECT AVGPrediction FROM ENTAVGPredictions WHERE Code = '{codeName}'");
                        int avgPrediction = GetPointsByCodeName(sbQueryAVG.ToString());

                        StringBuilder sbQueryMIN = new StringBuilder();
                        sbQueryMIN.Append($"SELECT MinPrediction FROM ENTMINPredictions WHERE Code = '{codeName}'");
                        int minPrediction = GetPointsByCodeName(sbQueryMIN.ToString());

                        if (point >= minPrediction && point <= avgPrediction)
                        {
                            prediction = (int)(((float)point / (float)avgPrediction) * 100);
                        }
                        else if (point > avgPrediction)
                        {
                            prediction = 100;
                        }

                        if (prediction != 0 && entPredictions.Count < 15)
                        {
                            entPredictions.Add(new ENTPrediction() { CodeName = codeName, Description = description, Prediction = prediction });
                        }

                    }
                }
                reader.Close();

                string query = "SELECT SubjectName FROM Subjects WHERE Number = '" + Number + "'";

                SubjectName = GetSubjectByNumber(query);

                entPredictions.Sort(delegate (ENTPrediction x, ENTPrediction y) {
                    return y.Prediction.CompareTo(x.Prediction);
                });

                foreach (var entPrediction in entPredictions)
                {
                    UniversitiesNames.Add(GetUniversityByCodeName(entPrediction.CodeName));
                }
            }
        }

        public int GetPointsByCodeName(string sbQuery)
        {
            int point = 0;
            using (SqlConnection sqlConnection = new SqlConnection(this._dbConnection))
            {
                sqlConnection.Open();
                SqlCommand command = new SqlCommand(sbQuery, sqlConnection);
                SqlDataReader reader = command.ExecuteReader();

                if (reader.HasRows)
                {
                    while (reader.Read())
                    {
                        point = Convert.ToInt32(reader.GetValue(0));
                    }
                }
            }

            return point;
        }

        private string GetSubjectByNumber(string query)
        {
            using (SqlConnection sqlConnection = new SqlConnection(this._dbConnection))
            {
                sqlConnection.Open();
                SqlCommand command = new SqlCommand(query, sqlConnection);
                SqlDataReader reader = command.ExecuteReader();

                if (reader.HasRows)
                {
                    if (reader.Read())
                    {
                        return reader.GetString(0);
                    }
                }
            }

            return null;
        }

        private string GetUniversityByCodeName(string codeName)
        {
            StringBuilder sbQeury = new StringBuilder();
            sbQeury.Append("SELECT UniversityName " +
                           "FROM Universities " +
                           "WHERE Id IN (SELECT UniversityId" +
                           "             FROM UniversityEducations" +
                           "             WHERE EducationId = (SELECT Id" +
                           "                                  FROM EducationPrCode" +
                           $"                                  WHERE CodeName = '{codeName}'));");
            using (SqlConnection sqlConnection = new SqlConnection(this._dbConnection))
            {
                sqlConnection.Open();
                SqlCommand command = new SqlCommand(sbQeury.ToString(), sqlConnection);
                SqlDataReader reader = command.ExecuteReader();

                if (reader.HasRows)
                {
                    if (reader.Read())
                    {
                        return reader.GetString(0);
                    }
                }
            }

            return null;
        }
    }

    public class ENTPrediction
    {
        public string CodeName { get; set; }
        public string Description { get; set; }
        public int Prediction { get; set; }
    }
}

Diplomka/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Diplomka.Models;
using Microsoft.EntityFrameworkCore;
using System.Runtime.CompilerServices;
using System.Text.RegularExpressions;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.Extensions.Options;
using System.Text;
using Microsoft.Data.SqlClient;

namespace Diplomka.Pages
{
    public class IndexModel : PageModel
    {
        private readonly DiplomDBContext _context;
        private readonly string _dbConnection = "Server=(localdb)\\MSSQLLocalDB; Database=DBDiplom; Trusted_Connection=True;";
        public IndexModel(DiplomDBContext context)
        {
            this._context = context;
        }
        public List<SelectListItem> Options { get; set; }
        public string SelectedSubject { get; set; }
        public string Points { get; set; }
        public void OnGet()
        {
            Options = _context.Subjects.Select(a =>
                                  new SelectListItem
                                  {
                                      Value = a.Number,
                                      Text = a.SubjectName
                                  }).ToList();
        }
        
        public IActionResult OnPost(string SelectedSubject, string points)
        {
            return RedirectToPage("AnalyzePage", new { number = SelectedSubject, points = points });
        }
    }
}

Diplomka/Pages/ProfilePage.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Diplomka.Pages
{
    public class ProfilePageModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Diplomka/Pages/AboutUs.cshtml
@page
@model Diplomka.Pages.AboutUsModel
@{
    Layout = "/Pages/Shared/_LayoutForAboutUs.cshtml";
}

@section Styles {
    <link rel="stylesheet" href="~/css/StyleForAboutUs.css" type="text/css">
}

@section Scripts {
    <script src="~/js/ScriptForUnline.js"></script>
    <script src="~/js/ScriptForCarousel.js"></script>
}

<div class="wrapper-page_aboutme">
    <div class="container-fluid d-flex justify-content-center">
        <div class="underline-text__wrapper">
            <h1 class="underline-text">Наша команда разработчиков</h1>
            <div class="unline unline__bistre"></div>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col d-flex justify-content-center align-items-center">
            <div class="slider__wrapper">
                <div class="slider-screen__wrapper d-flex">
                    <div class="slider-item slider-item__active">
                        <div class="slider-item__image first-item"></div>
                        <div class="slider-item__info">
                            <h3>Vitaliy</h3>
                        </div>
                    </div>
                    <div class="slider-item">
                        <div class="slider-item__image second-item"></div>
                        <div class="slider-item__info">
                            <h3>Temirlan</h3>
                        </div>
                    </div>
                    <div class="slider-item">
                        <div class="slider-item__image third-item"></div>
                        <div class="slider-item__info">
                            <h3>Alex</h3>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="container-fluid d-flex justify-content-center">
                <div class="underline-text__wrapper">
                    <h2 class="underline-text">О команде</h2>
                    <div class="unline unline__bistre"></div>
                </div>
            </div>
            <div class="container-fluid">
                <p>
                        Команда разработки веб-сайта "AidENT" рада категорически приветствовать новых пользователей! Наша задача - помочь поступающим в выборе
                        их будущего. Каждый абитуриент в пору сдачи финального тестирования испытывает чувства волнения, сомнения в самопределении, неуверенность в подготовке 
                        и кучу других эмоций. "AidENT" помимо того, что может рассчитать шанс на поступление, в последствии может стать неотъемлемым инструментом в
                        подготовке к ЕНТ. Планируется добавление возможности прохождения пробных тестирований, добавление справочных материалов по предметам,
                        университетам и специальностям.
                </p>
                <p>
                        Познакомимся ближе: позвольте представиться, мы - создатели и разработчики веб-приложения "AidENT".
                        Еволенко Алексей - специалист по анализу данных. Разработал непосредственный алгоритм машинного обучения предсказания баллов, на основе которого будет расчет прогнозов.
                        Мендешев Темирлан - backend-специалист. Создал базу данных пользователей, университетов, специальностей, разработал функционал сайта, расчет прогнозов после анализа.
                        Трусов Виталий - frontend-специалист. Верстальщик сайта, разработал уникальный стиль и интерфейс приложения, а также отображение посчитанных прогнозов. 
                        Каждый из нас показал компетентность в своей сфере разработке. Собрав воедино все отдельные компоненты разработки, получился полноценный, функционирующий веб-сайт "AidENT".
                </p>
                <p>
                        Также у нас имеется возможность вступить в команду разработчиков, заполнив форму ниже. Если ты крутой специалист с идеями, присоеденияйся,
                        вместе мы расширим возможности приложения и поможем поступающим, ведь мы когда-то тоже застали этот непростой период.
                </p>
            </div>
        </div>
    </div>
    <div class="row row-form">
        <div class="background-form"></div>
        <div class="col-6 d-flex flex-column justify-content-center align-items-center">
            <div class="underline-text__wrapper">
                <h2 class="underline-text underline-text__white">Желаете пополнить нашу команду? Заполните форму!</h2>
                <div class="unline unline__bisque3"></div>
            </div>
        </div>
        <div class="col-6">
            <div class="wrapper-form container-fluid d-flex justify-content-around-center">
                <div class="form-container">
                    <form method="post">
                        <div class="form-group">
                            <label for="authorNameId">Напишите имя:</label>
                            <input type="text" class="form-control" id="authorNameId" name="name" required>
                        </div>
                        <div class="form-group">
                            <label for="emailId">Напишите ваш адрес эл. почты:</label>
                            <input type="email" class="form-control" id="emailId" aria-describedby="descEmail" name="email" required>
                            <small id="descEmail">Указывайте почту с доменом</small>
                        </div>
                        <div class="form-group">
                            <label for="msgId">Напишите кратко ваше резюме:</label>
                            <textarea class="form-control" id="msgId" name="message" required></textarea>
                        </div>
                        <div class="form-group">
                            <label for="dateId">Ваша дата рождения:</label>
                            <input type="date" class="form-control" id="dateId" name="date" required>
                        </div>
                        <button class="btn btn-outline-dark mt-2" type="submit" asp-page-handler="SendForm">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

Diplomka/Pages/AdminPage.cshtml
@page "{namePage?}"
@model Diplomka.Pages.AdminPageModel
@{
    Layout = "/Pages/Shared/_LayoutForAdminPage.cshtml";
}

@if(Model.IsSuccess) {
    <div class="container-fluid d-flex justify-content-center">
        <h1>Данные были добавлены успешно</h1>
    </div>
}

@if(Model.TypePage == "FillPoints") {
    <form method="post" enctype="multipart/form-data">
        <div class="form-group">
            <label for="fileInputId">Добавьте файл с баллами:</label>
            <input type="file" class="form-control" id="fileInputId" asp-for="UploadFile" />
        </div>
        <div class="form-group mt-3">
            <label for="yearInputId">Год ЕНТ:</label>
            <input type="text" class="form-control" id="yearInputId" name="year" aria-describedby="yearHelp" />
            @if(Model.IsYearExist) {
                <small id="yearHelp" class="form-text text-danger">Эта дата уже существует</small>
            }
        </div>
        <button class="btn btn-outline-dark mt-3" type="submit">Добавить данные</button>
    </form>

    <form method="post">
        <button class="btn btn-outline-dark mt-2" type="submit" asp-page-handler="CreatePredictions">Проанализировать</button>
    </form>
}else if(Model.TypePage == "Download") {
    <form method="post" class="mt-3">
        <button class="btn btn-outline-dark" asp-page-handler="Download">Скачать предсказанные баллы</button>
    </form>
    <div class="row">
        <h1>Предсказанные баллы</h1>
    </div>
    <div class="row">
        <div class="col-6 mt-3">
            <table class="table table-striped table-dark">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Код предмета</th>
                        <th>Средний балл</th>
                    </tr>
                </thead>
                <tbody>
                    @for(int i = 0; i < Model.AVGPrediction.Count; i++) {
                        <tr>
                            <th>@(i+1)</th>
                            <th>@(Model.AVGPrediction[i].Code)</th>
                            <th>@(Model.AVGPrediction[i].AVGPrediction)</th>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <div class="col-6">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Код предмета</th>
                        <th>Минимальный балл</th>
                    </tr>
                </thead>
                <tbody>
                    @for(int i = 0; i < Model.MINPrediction.Count; i++) {
                        <tr>
                            <th>@(i+1)</th>
                            <th>@(Model.MINPrediction[i].Code)</th>
                            <th>@(Model.MINPrediction[i].MINPrediction)</th>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
} else if (Model.TypePage == "Resumes") {
    <div class="row">
        <div class="col-6">
            <h1>Поданные резюме</h1>
        </div>
        <div class="col-6">
            <form method="post">
                <button type="submit" class="btn btn-outline-dark" asp-page-handler="SendResumes">Отправить email hr-у</button>
            </form>
        </div>
    </div>
    <div class="row">
           <table class="table table-striped table-dark">
               <thead>
                   <tr>
                       <th>#</th>
                       <th>Имя</th>
                       <th>Email</th>
                       <th>О себе</th>
                       <th>Birthday</th>
                   </tr>
               </thead>
               <tbody>
                   @for(int i = 0; i < Model.Resumes.Count; i++) {
                       <tr>
                           <th>@(i + 1)</th>
                           <th>@(Model.Resumes[i].AuthorName)</th>
                           <th>@(Model.Resumes[i].Email)</th>
                           <th>@(Model.Resumes[i].About)</th>
                           <th>@(Model.Resumes[i].Birthday.ToShortDateString())</th>
                       </tr>
                   }
               </tbody>
           </table>
       </div>
} else {
    <div>Страница в разработке</div>
}

Diplomka/Pages/AnalyzePage.cshtml
@page "{number}/{points}"
@model Diplomka.Pages.AnalyzePageModel
@{
    Layout = "/Pages/Shared/_LayoutForAnalyzePage.cshtml";
}



@section Scripts{
    <script src="~/js/CircleProgressBar.js"></script>
}

    <div class="row">
        <div class="subject-container container-fluid d-flex justify-content-center">
            <div class="subject-container__wrapper d-flex justify-content-center align-items-center">
                <p class="subject-name nameFont">@Model.SubjectName</p>
            </div>
        </div>
    </div>
    @if(Model.entPredictions.Count > 0) {
    <div class="row">
        <div class="col-6">
            @foreach (var model in Model.entPredictions)
            {
                <div class="row d-flex bgCream mt-5 ms-3 list-container">
                    <div class="code-container">
                        <div class="code-container__wrapper container-fluid d-flex">
                            <p class="nameFont"><strong>@(model.CodeName)</strong></p>
                            <p class="nameFont ms-2"><strong>@(model.Description)</strong></p>
                        </div>
                    </div>
                    <div class="prediction-container">
                        <div class="prediction-container__wrapper">
                            <div class="progress-container">
                                <svg class="progress-ring" height="120" width="120">
                                    <circle class="progress-ring__circle" stroke="#854442" stroke-width="4" cx="60" cy="60" r="52" fill="transparent"></circle>
                                </svg>
                            </div>
                            <div class="prediction-number container">
                                <p>@(model.Prediction)%</p>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
        <div class="col-6">
            @foreach (var item in Model.UniversitiesNames)
            {
                <div class="row d-flex justify-content-center align-items-center bgCream mt-5 ms-3 list-container">
                    <p>@(item)</p>
                </div>
            }
        </div>
    </div>
    }
    else {
        <div class="row">
            <div class="container-fluid d-flex justify-content-center mt-5">
                <h1 style="color:white">Невозможно поступить на грант.</h1>
            </div>
        </div>
    }

Diplomka/Pages/LogAndRegPage.cshtml
@page "{namePage}"
@model Diplomka.Pages.LogAndRegPageModel
@{
    Layout = "/Pages/Shared/_LayoutForLogAndRegPage.cshtml";
}

@section Styles {
    <link href="~/css/LogAndRegPageStyles.css" rel="stylesheet" type="text/css"/>
}

<div class="mainWrapper row">
    <div class="col-5 left-side__wrapper d-flex justify-content-center align-items-center">
        <div class="form-container__wrapper">
            <div class="form-container w-100">
                @if(Model.TypePage == "Log") {
                    <div class="d-flex justify-content-center container-fluid">
                        <p1 class="first_text">Вход</p1>
                    </div>
                    <form method="post">
                        <div class="log-form__wrapper">
                            <div class="login-box__log container-fluid">
                                <div class="container-fluid">
                                    <p1 class="input-sign__word">Логин</p1>
                                </div>
                                <input name="loginLog" class="w-100 input-sign__box" type="text" id="input-login__id" placeholder="Введите логин*" required/>
                            </div>
                            <div class="password-box__log container-fluid">
                                <div class="container-fluid">
                                    <p1 class="input-sign__word">Пароль</p1>
                                </div>
                                <input name="psswdLog" class="w-100 input-sign__box" type="password" id="input-password__id" placeholder="Введите пароль*" required/>
                            </div>
                            <div class="w-100 mt-4">
                                <a class="forget-password-ask" href="@Url.Page("LogAndRegPage", new { namePage="Forget"})">Забыли пароль?</a>
                                <div class="btns-container__wrapper d-flex flex-column justify-content-center container-fluid mt-3">
                                    <button type="submit" class="darkBlueButton btns-logAndReg" asp-page-handler="Log">
                                        <span class="font-weight-bold-white-text">Войти</span>
                                    </button>
                                    <a href="@Url.Page("LogAndRegPage", new { namePage = "Reg" })" class="btn-signin btns-logAndReg d-flex flex-column justify-content-center align-items-center mt-3">
                                        <span class="font-weight-bold-signin d-flex justify-content-center">Зарегистрироваться</span>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </form>
                } else if(Model.TypePage == "Reg") {
                    <div class="d-flex justify-content-center container-fluid">
                        <p1 class="first_text">Регистрация</p1>
                    </div>
                    <form method="post">
                        <div class="signup-container">
                            <div class="name-box__reg container-fluid">
                                <div class="container-fluid">
                                    <p1 class="input-sign__word">Имя</p1>
                                </div>
                                <input name="nameReg" class="w-100 input-sign__box" type="text" id="input-name__id" placeholder="Введите имя*" required/>
                            </div>
                            <div class="surname-box__reg container-fluid">
                                <div class="container-fluid">
                                    <p1 class="input-sign__word">Фамилия</p1>
                                </div>
                                <input name="surnameReg" class="w-100 input-sign__box" type="text" id="input-surname__id" placeholder="Введите фамилию*" required/>
                            </div>
                            <div class="email-box__reg container-fluid">
                                <div class="container-fluid">
                                    <p1 class="input-sign__word">Email</p1>
                                </div>
                                <input name="emailReg" class="w-100 input-sign__box" type="text" id="input-email__id" placeholder="Введите email*" required/>
                            </div>
                            <div class="login-box__reg container-fluid">
                                <div class="container-fluid">
                                    <p1 class="input-sign__word">Логин</p1>
                                </div>
                                <input name="loginReg" class="w-100 input-sign__box" type="text" id="input-login__id" placeholder="Введите логин*" required/>
                            </div>
                            <div class="password-box__reg container-fluid">
                                <div class="container-fluid">
                                    <p1 class="input-sign__word">Пароль</p1>
                                </div>
                                <input name="psswdReg" class="w-100 input-sign__box" type="password" id="input-password__id" placeholder="Введите пароль*" required/>
                            </div>
                            <div class="rpassword-box__reg container-fluid">
                                <div class="container-fluid">
                                    <p1 class="input-sign__word">Повторите пароль</p1>
                                </div>
                                <input name="rpsswdReg" class="w-100 input-sign__box" type="password" id="input-rpasswprd__id" placeholder="Повторите пароль*" required/>
                            </div>
                            <div class="w-100 mt-4">
                                <div class="btns-container__wrapper d-flex flex-column justify-content-center container-fluid">
                                    <button type="submit" class="darkBlueButton btns-logAndReg" asp-page-handler="Reg">
                                        <span class="font-weight-bold-white-text">Зарегистрироваться</span>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </form>
                } else if (Model.TypePage == "Out"){
                    RedirectToPage("Index");
                    }
                else
                {
                    <div class="d-flex justify-content-center container-fluid">
                        <p1 class="first_text">Забыли пароль?</p1>
                    </div>
                    <form method="post">
                        <div class="forget-psswd__wrapper">
                            <div class="email-box__forget container-fluid">
                                <p1 class="input-sign__word">Email</p1>
                            </div>
                            <input name="emailForget" class="w-100 input-sign__box" type="text" id="input-emailForget__id" placeholder="Впишите email*" />
                        </div>
                        <div class="w-100">
                            <div class="btns-container__wrapper d-flex flex-column justify-content-center container-fluid mt-3">
                                <button type="submit" class="btns-logAndReg darkBlueButton" asp-page-handler="Forget">
                                    <span class="font-weight-bold-white-text">Получить код</span>
                                </button>
                            </div>
                        </div>
                    </form>
                }
            </div>
        </div>
    </div>
    <div class="col-7  right-side__wrapper">
        <div class="right-side">
        </div>
    </div>
</div>

Diplomka/Pages/ProfilePage.cshtml
@page
@model Diplomka.Pages.ProfilePageModel
@{
    Layout = "/Pages/Shared/_LayoutForMainPage.cshtml";
}
@section Styles {
    <link href="~/css/MainPageStyles.css" rel="stylesheet" type="text/css" />
    <link href="~/css/testbox.css" rel="stylesheet" type="text/css" />

}

@section Scripts{
    <script src="~/js/MainPage.js"></script>
    <script type="module" src="https://ajax.googleapis.com/ajax/libs/model-viewer/3.0.1/model-viewer.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
}


    <h2>Приветсвую, @(HttpContext.Session.GetString("Name")) @(HttpContext.Session.GetString("Surname")) </h2>


<h4>Страница в разработке</h4>